const classes = {
  Base: [
    'bg-white',
    'dark:bg-gray-800',
    'relative',
    'w-full',
    'border',
    'border-gray-300',
    'dark:border-gray-700',
    'rounded-md',
    'shadow-sm',
    'pl-3',
    'pr-10',
    'py-2',
    'text-left',
    'cursor-default',
    'focus:outline-none',
    'focus:ring-1',
    'focus:ring-brand',
    'focus:border-brand',
    'sm:text-sm',
  ],
  InputError: [
    'border-red-300',
    'text-red-900',
    'focus:ring-red-500',
    'focus:border-red-500',
    'dark:border-red-700',
  ],
  Content: [
    'absolute',
    'inset-y-0',
    'right-0',
    'flex',
    'items-center',
    'pr-2',
    'pointer-events-none',
  ],
  Label: [
    'block',
    'text-sm',
    'font-medium',
    'text-gray-700',
    'dark:text-gray-300',
  ],
  Options: [
    'absolute',
    'mt-1',
    'w-full',
    'bg-gray-200',
    'dark:bg-gray-800',
    'shadow-lg',
    'max-h-60',
    'rounded-md',
    'py-1',
    'text-base',
    'ring-1',
    'ring-black',
    'ring-opacity-5',
    'overflow-auto',
    'focus:outline-none',
    'sm:text-sm',
  ],
  OptionsOpen: [
    'z-100'
  ],
  Option: [
    'cursor-default',
    'select-none',
    'relative',
    'py-2',
    'pl-3',
    'pr-9',
    'hover:bg-brand',
  ],
  OptionPlaceholder: [
    'text-gray-600',
    'dark:text-gray-400',
    'cursor-default',
    'select-none',
    'relative',
    'py-2',
    'pl-3',
    'pr-9',
    'hover:bg-brand',
  ],
  OptionActive: ['text-white', 'bg-brand'],
  OptionNonActive: ['text-gray-900', 'dark:text-gray-300'],
  CheckIcon: [
    'absolute',
    'inset-y-0',
    'right-0',
    'flex',
    'items-center',
    'pr-4',
  ],
  CheckIconActive: 'text-white dark:text-gray-200',
  CheckIconNonActive: 'text-brand',
}
export default classes
